/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the LocoLaser tool.
 * It should not be modified by hand.
 */

package ru.pocketbyte.locolaser.example.repository

import android.content.Context
import ru.pocketbyte.locolaser.example.R
import ru.pocketbyte.locolaser.example.repository.StringRepository

public class AndroidStringRepository(private val context: Context): StringRepository {

    override public val app_name: String
        get() = this.context.getString(R.string.app_name)

    override public val screen_main_hello_text: String
        get() = this.context.getString(R.string.screen_main_hello_text)

}