/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the LocoLaser tool.
 * It should not be modified by hand.
 */

package ru.pocketbyte.locolaser.example.repository

import kotlinx.cinterop.*
import platform.Foundation.*
import ru.pocketbyte.locolaser.example.repository.StringRepository

public class IosStringRepository(private val bundle: NSBundle, private val tableName: String): StringRepository {

    constructor(bundle: NSBundle) : this(bundle, "Localizable")
    constructor(tableName: String) : this(NSBundle.mainBundle(), tableName)
    constructor() : this(NSBundle.mainBundle(), "Localizable")

    override public val app_name: String
        get() = this.bundle.localizedStringForKey("app_name", "", this.tableName)

    override public val screen_main_hello_text: String
        get() = this.bundle.localizedStringForKey("screen_main_hello_text", "", this.tableName)

}