/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the LocoLaser tool.
 * It should not be modified by hand.
 */

package ru.pocketbyte.locolaser.example.repository

interface StringRepository {

    /**
    * locolaser-kotlin-multiplatform-example
    */
    val app_name: String

    /**
    * Hello Kotlin!
    */
    val screen_main_hello_text: String

    /**
    * Plural: %d apples
    */
    fun screen_main_plural_string(count: Int): String

}